export const GET_ALL_CATEGORIES_REQUEST: string = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_RESPONSE: string =
  "GET_ALL_CATEGORIES_RESPONSE";

export const GET_CATEGORY_PRODUCTS_REQUEST: string =
  "GET_CATEGORY_PRODUCTS_REQUEST";
export const GET_CATEGORY_PRODUCTS_RESPONSE: string =
  "GET_CATEGORY_PRODUCTS_RESPONSE";
